title: My Blog
author: Xavier Delamotte
description: Random stuff I want to share
baseurl: /blog # the subpath of your site, e.g. /blog
url: "https://xade.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  x4d3
# Build settings
plugins:
  - jekyll-feed
  - jekyll-postfiles
search: true

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

permalink: /:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
